# For our organization 
- name: 'invite me to organisation'
  color: '#D4ECDD'


# issue bounty 
- name: good first issue
  description: 'Good for newcomers'
  color: '#7057ff'
- name: up-for-grabs
  description: 'Open for work'
  color: '#93FFD8'
- name: hacktoberfest
  description: issue up for hactoberfest participation 
  color: '#DE834D'
- name: 'beginner'
  description: 'issue suitable for beginners'
  color: '#FAEDC6'
- name: first-timers-only
  color: '#7900FF'

# discussion labels 
- name: '📄 Maintainer Program 2021'
  description: 'Mark Submissions for 2021 Maintainer Program'
  color: '#FEF2C0'
- name: 'Maintainers Program 2021 proposal - accepted'
  description: 'Accepted Maintainers Program 2021 proposal'
  color: '#D60398'

# effort labels
- name: 'effort: 1'
  color: '#91ca55'
- name: 'effort: 2'
  color: '#c2e2a2'
- name: 'effort: 3'
  color: '#e9f4dc'
- name: 'effort: 5'
  color: '#fef6d7'
- name: 'effort: 8'
  color: '#fef2c0'
- name: 'effort: 13'
  color: '#fbca04'

# Issue type labels 
- name: 'type: bug'
  description: ' Something isn''t working as intended'
  color: '#FF5C58'
- name: 'type: feature'
  description: 'new feature '
  color: '#B4FE98'
- name: 'type: chore'
  description: boring work
- name: 'type: doc'
  description: ' Improvements or additions to documentation '
  color: '#3D56B2'
- name: 'type: enhancement'
  description: small upgrade
  color: '#FFE194'
- name: 'type: awaiting triage'
  description: ' Awaiting triage from a maintainer '
  color: '#CDF0EA'
- name: 'type: idea'
  description: 'A new idea '
  color: '#FFF7AE'

# work labels
- name: 'work: chaotic'
  color: '#fbca04'
  description: The situation is chaotic, novel practices used.
  aliases:
    - chaotic
- name: 'work: complex'
  color: '#d4c5f9'
  description: The situation is complex, emergent practices used.
  aliases:
    - complex
- name: 'work: complicated'
  color: '#ffb8c6'
  description: The situation is complicated, good practices used.
  aliases:
    - complicated
- name: 'work: obvious'
  color: '#91ca55'
  description: The situation is obvious, best practices used.
  aliases:
    - obvious