# Common label
- name: help wanted
  description: ' Extra attention is needed '
  color: '#4E9F3D'
- name: good first issue
  description: ' Good for newcomers '
  color: '#BC8CF2'
- name: wontfix
  description: ' This will not be worked on '
- name: need planning
  description: 'serious planing is needed '
  color: '#FBD148'

# Issue type labels 
- name: 'type: bug'
  description: ' Something isn''t working as intended'
  color: '#FF5C58'
- name: 'type: feature'
  description: 'new feature '
  color: '#B4FE98'
- name: 'type: chore'
  description: boring work
- name: 'type: doc'
  description: ' Improvements or additions to documentation '
  color: '#3D56B2'
- name: 'type: enhancement'
  description: small upgrade
  color: '#FFE194'
- name: 'type: awaiting triage'
  description: ' Awaiting triage from a maintainer '
  color: '#CDF0EA'
- name: 'type: idea'
  description: 'A new idea '
  color: '#FFF7AE'


# priority labels
- name: 'priority: now'
  color: d73a4a
  aliases:
    - 'priority: critical'
    - 'Priority: Critical'
- name: 'priority: soon'
  color: ffb8c6
  aliases:
    - 'priority: medium'
    - 'Priority: Medium'
- name: 'priority: 2day'
  color: fbca04
  aliases:
    - 'priority: high'
    - 'Priority: High'

# effort labels
- name: 'effort: 1'
  color: 91ca55
- name: 'effort: 2'
  color: c2e2a2
- name: 'effort: 3'
  color: e9f4dc
- name: 'effort: 5'
  color: fef6d7
- name: 'effort: 8'
  color: fef2c0
- name: 'effort: 13'
  color: fbca04

# work labels
- name: 'work: chaotic'
  color: fbca04
  description: The situation is chaotic, novel practices used.
  aliases:
    - chaotic
- name: 'work: complex'
  color: d4c5f9
  description: The situation is complex, emergent practices used.
  aliases:
    - complex
- name: 'work: complicated'
  color: ffb8c6
  description: The situation is complicated, good practices used.
  aliases:
    - complicated
- name: 'work: obvious'
  color: 91ca55
  description: The situation is obvious, best practices used.
  aliases:
    - obvious
- name: 'invite me to organisation'
  color: 'D4ECDD'


# pr labels 
- name: 🚧 WIP
  color: '#FF616D'
- name: ready for review
  description: pr ready to be review
  color: '#D5EEBB'
